#!/bin/bash
# Copyright © 2012-2013 Martin Ueding <dev@martin-ueding.de>

set -e
set -u

if qdbus | grep -i clementine
then
	qdbus org.mpris.clementine /Player Stop
fi

qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock
sleep 4
xset dpms force off
