#!/usr/bin/fish
# Copyright © 2012-2014 Martin Ueding <dev@martin-ueding.de>

if qdbus | grep -i clementine
    qdbus org.mpris.clementine /Player Stop
end

set dbus_parameters org.freedesktop.ScreenSaver /ScreenSaver Lock

if qdbus
    qdbus $dbus_parameters
else if qdbus -qt4
    qdbus -qt4 $dbus_parameters
end

sleep 4
xset dpms force off
