#!/usr/bin/fish
# Copyright © 2012-2014 Martin Ueding <dev@martin-ueding.de>

if qdbus | grep -i clementine
    qdbus org.mpris.clementine /Player Stop
end

if qdbus
    qdbus org.freedesktop.ScreenSaver /ScreenSaver Lock
end
sleep 4
xset dpms force off
